[project]
name = "image-analysis-and-qa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.121.2",
    "pillow>=12.0.0",
    "python-multipart>=0.0.20",
    "ultralytics>=8.3.229",
    "uvicorn>=0.38.0",
    "pydantic-ai>=0.0.14",
    "google-generativeai>=0.8.3",
    "python-dotenv>=1.0.0",
    "nest-asyncio>=1.6.0",
]
